### ISSUE TITLE
error with I3TruthExtractor() with level 2 monte carlo data

### ISSUE THREAD

**Issue by MortenHolmRep** [graphnet-team/graphnet#307]
**Describe the bug**
When running convert_i3_to_sql.py I encounter an I3-related error.

**To Reproduce**
Steps to reproduce the behaviour:
1. Enter icetray on cobalt
2. In `../examples/convert_i3_to_sql.py` specify:
- datapath:  `/mnt/lfs6/sim/IceCube/2012/filtered/level2/neutrino-generator/11069/08000-08999/`
- gcd: `/mnt/lfs6/sim/IceCube/2012/filtered/level2/neutrino-generator/11069/08000-08999/GeoCalibDetectorStatus_2012.56063_V1.i3.gz`
- pulse: "InIceDSTPulses"
3. Run `python convert_i3_to_sql.py`
4. See the error

**Expected behaviour**
It should generate the database

**Full traceback**
Please include the full error message to allow for debugging
```
Traceback (most recent call last):
  File "/data/user/mholm/graphnet/studies/Moon_Pointing_Analysis/data/convert_i3_to_sqlite.py", line 83, in <module>
    main_icecube86()
  File "/data/user/mholm/graphnet/studies/Moon_Pointing_Analysis/data/convert_i3_to_sqlite.py", line 46, in main_icecube86
    converter(paths)
  File "/mnt/ceph1-npx/user/mholm/graphnet/src/graphnet/data/dataconverter.py", line 210, in __call__
    self.execute(filesets)
  File "/mnt/ceph1-npx/user/mholm/graphnet/src/graphnet/data/dataconverter.py", line 277, in execute
    pool = self._iterate_over_individual_files(filesets)
  File "/mnt/ceph1-npx/user/mholm/graphnet/src/graphnet/data/dataconverter.py", line 317, in _iterate_over_individual_files
    self._process_file, tqdm(args, unit="file(s)", colour="green")
  File "/mnt/ceph1-npx/user/mholm/graphnet/src/graphnet/data/dataconverter.py", line 71, in wrapper
    output_file = process_method(self, *args)
  File "/mnt/ceph1-npx/user/mholm/graphnet/src/graphnet/data/dataconverter.py", line 361, in _process_file
    data = self._extract_data(fileset)
  File "/mnt/ceph1-npx/user/mholm/graphnet/src/graphnet/data/dataconverter.py", line 419, in _extract_data
    results = self._extractors(frame)
  File "/mnt/ceph1-npx/user/mholm/graphnet/src/graphnet/data/extractors/i3extractor.py", line 81, in __call__
    return [extractor(frame) for extractor in self]
  File "/mnt/ceph1-npx/user/mholm/graphnet/src/graphnet/data/extractors/i3extractor.py", line 81, in <listcomp>
    return [extractor(frame) for extractor in self]
  File "/mnt/ceph1-npx/user/mholm/graphnet/src/graphnet/data/extractors/i3truthextractor.py", line 152, in __call__
    ) = self._get_primary_track_energy_and_inelasticity(frame)
  File "/mnt/ceph1-npx/user/mholm/graphnet/src/graphnet/data/extractors/i3truthextractor.py", line 352, in _get_primary_track_energy_and_inelasticity
    energy_track = sum(track.total_energy for track in tracks)
  File "/mnt/ceph1-npx/user/mholm/graphnet/src/graphnet/data/extractors/i3truthextractor.py", line 352, in <genexpr>
    energy_track = sum(track.total_energy for track in tracks)
RuntimeError: "Hadrons" has no mass implemented. Cannot get total energy. (in double I3Particle::GetTotalEnergy() const)
```

**Comment by asogaard** [comment]
I think this is the same as #282

**Comment by RasmusOrsoe** [comment]
@MortenHolmRep @asogaard yes, this has been fixed using an except statement. If you update to main, this should be gone.

**Comment by MortenHolmRep** [comment]
> @MortenHolmRep @asogaard yes, this has been fixed using an except statement. If you update to main, this should be gone.

I will update at once :)
