### ISSUE TITLE
WandB fails when config is too large

### ISSUE THREAD

**Issue by Peterandresen12** [graphnet-team/graphnet#316]
I tried to run benchmark.py, with WandB, but got an error because the config is too large, probably due to the train_selection array being too big. `ERROR Error while calling W&B API: run config cannot exceed 15 MB (<Response [400]>)`

Perhaps the data selections does not need to be uploaded to WandB?

The full message is: 
```(graphnet) [peter@hep04 northern_tracks]$ python benchmark.py 
graphnet: INFO     2022-10-19 10:33:19 - get_logger - Writing log to logs/graphnet_20221019-103308.log
graphnet: WARNING  2022-10-19 10:33:25 - warn_once - `icecube` not available. Some functionality may be missing.
wandb: Currently logged in as: peterandresen (graphnet-team). Use `wandb login --relogin` to force relogin
wandb: wandb version 0.13.4 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.13.1
wandb: Run data is saved locally in ./wandb/wandb/run-20221019_103334-47u9ascy
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run woven-water-2
wandb: ⭐️ View project at https://wandb.ai/graphnet-team/NortherenTracks_Benchmark
wandb: 🚀 View run at https://wandb.ai/graphnet-team/NortherenTracks_Benchmark/runs/47u9ascy
wandb: WARNING Serializing object of type list that is 14743672 bytes
wandb: WARNING Serializing object of type list that is 4914592 bytes
wandb: WARNING Serializing object of type list that is 4914600 bytes
wandb: WARNING Serializing object of type list that is 15673400 bytes
wandb: WARNING Serializing object of type list that is 5429640 bytes
wandb: WARNING Serializing object of type list that is 5429640 bytes
graphnet: INFO     2022-10-19 10:33:54 - train - features: ['dom_x', 'dom_y', 'dom_z', 'dom_time', 'charge', 'rde', 'pmt_area']
graphnet: INFO     2022-10-19 10:33:54 - train - truth: ['energy', 'energy_track', 'position_x', 'position_y', 'position_z', 'azimuth', 'zenith', 'pid', 'elasticity', 'sim_type', 'interaction_type', 'interaction_time', 'inelasticity']
graphnet: WARNING  2022-10-19 10:33:54 - SQLiteDataset._remove_missing_columns - Removing the following (missing) truth variables: interaction_time
graphnet: WARNING  2022-10-19 10:33:54 - SQLiteDataset._remove_missing_columns - Removing the following (missing) truth variables: interaction_time
graphnet: WARNING  2022-10-19 10:33:54 - SQLiteDataset._remove_missing_columns - Removing the following (missing) truth variables: interaction_time
/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/core/lightning.py:22: LightningDeprecationWarning: pytorch_lightning.core.lightning.LightningModule has been deprecated in v1.7 and will be removed in v1.9. Use the equivalent class from the pytorch_lightning.core.module.LightningModule class instead.
  rank_zero_deprecation(
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]

  | Name      | Type            | Params
----------------------------------------------
0 | _detector | IceCubeDeepCore | 0     
1 | _gnn      | DynEdge         | 1.3 M 
2 | _tasks    | ModuleList      | 258   
----------------------------------------------
1.3 M     Trainable params
0         Non-trainable params
1.3 M     Total params
5.376     Total estimated model params size (MB)
Epoch  0:   0%|                                                                                                            | 0/4800 [00:00<?, ? batch(es)/s]wandb: ERROR Error while calling W&B API: run config cannot exceed 15 MB (<Response [400]>)
Thread SenderThread:
Traceback (most recent call last):
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/wandb/apis/normalize.py", line 25, in wrapper
    return func(*args, **kwargs)
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 1465, in upsert_run
    response = self.gql(
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 113, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 204, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 51, in run
    self._run()
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 95, in _run
    self._debounce()
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/wandb/sdk/internal/internal.py", line 316, in _debounce
    self._sm.debounce()
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 387, in debounce
    self._debounce_config()
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 393, in _debounce_config
    self._api.upsert_run(
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/wandb/apis/normalize.py", line 27, in wrapper
    raise CommError(err.response, err)
wandb.errors.CommError: <Response [400]>
wandb: ERROR Internal wandb error: file data was not synced
Epoch  0: 100%|█████████████████████████████████████████████████████████████████████████████████████| 4800/4800 [09:03<00:00,  8.83 batch(es)/s, loss=-1.22]Traceback (most recent call last):██████████████████████████████████████████████████████████████████████████████| 1200/1200 [01:17<00:00, 15.53 batch(es)/s]
  File "benchmark.py", line 204, in <module>
    main()
  File "benchmark.py", line 200, in main
    train(config)
  File "benchmark.py", line 142, in train
    trainer.fit(model, training_dataloader, validation_dataloader)
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 735, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1166, in _run
    results = self._run_stage()
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1252, in _run_stage
    return self._run_train()
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1283, in _run_train
    self.fit_loop.run()
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 271, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 201, in run
    self.on_advance_end()
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 241, in on_advance_end
    self._run_validation()
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 299, in _run_validation
    self.val_loop.run()
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 207, in run
    output = self.on_run_end()
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 198, in on_run_end
    self.trainer._logger_connector.log_eval_end_metrics(all_logged_outputs)
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/logger_connector/logger_connector.py", line 142, in log_eval_end_metrics
    self.log_metrics(metrics)
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/logger_connector/logger_connector.py", line 109, in log_metrics
    logger.log_metrics(metrics=scalar_metrics, step=step)
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/utilities/rank_zero.py", line 32, in wrapped_fn
    return fn(*args, **kwargs)
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/loggers/wandb.py", line 390, in log_metrics
    self.experiment.log(dict(metrics, **{"trainer/global_step": step}))
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 289, in wrapper
    return func(self, *args, **kwargs)
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 255, in wrapper
    return func(self, *args, **kwargs)
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1591, in log
    self._log(data=data, step=step, commit=commit)
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1375, in _log
    self._partial_history_callback(data, step, commit)
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1259, in _partial_history_callback
    self._backend.interface.publish_partial_history(
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 553, in publish_partial_history
    self._publish_partial_history(partial_history)
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 67, in _publish_partial_history
    self._publish(rec)
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py", line 51, in _publish
    self._sock_client.send_record_publish(record)
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_record_publish
    self.send_server_request(server_req)
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 84, in send_server_request
    self._send_message(msg)
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 81, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 61, in _sendall_with_error_handle
    sent = self._sock.send(data[total_sent:])
BrokenPipeError: [Errno 32] Broken pipe
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 81, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/groups/icecube/peter/anaconda3/envs/graphnet/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 61, in _sendall_with_error_handle
    sent = self._sock.send(data[total_sent:])
BrokenPipeError: [Errno 32] Broken pipe```

**Comment by asogaard** [comment]
Yeah, I wouldn't call this a bug _per se_. It's just that `WandbLogger` has some limitations that we need to navigate.

I think your options are to:

1. not log the training selection; 
2. log the test selection instead, as it should be considerably smaller; 
3. encode the selection in the data pipeline such that the train/test label is a column in your database rather than a separate array, and then just log this column name; or 
4. implement and log the selection as a reproducible prescription (e.g., `test = event_no % 5 == 0` and `train = not test`) rather than as an explicit array of indices. 

I don't think (1) is a good option, but (2-4) could all work and I think they are all pretty straightforward to do.
