### ISSUE TITLE
Training direction fails with assertion error

### ISSUE THREAD

**Issue by sathanas31** [graphnet-team/graphnet#357]
**Describe the bug**
When training on `/data/ana/graphnet/tmp/dev_lvl5_NuE_NuMu_NuTau_Mirco/data/dev_lvl5_NuE_NuMu_NuTau_Mirco.db` using this script https://github.com/sathanas31/graphnet/blob/testing/examples/train_direction_reconstruction.py I get the following error

```GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Missing logger folder: /scratch/condor/dir_41646/lightning_logs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [4]

  | Name        | Type            | Params
------------------------------------------------
0 | _detector   | IceCubeDeepCore | 0     
1 | _gnn        | DynEdge         | 1.4 M 
2 | _tasks      | ModuleList      | 258   
3 | _coarsening | DOMCoarsening   | 0     
------------------------------------------------
1.4 M     Trainable params
0         Non-trainable params
1.4 M     Total params
5.530     Total estimated model params size (MB)
`Trainer.fit` stopped: `max_epochs=5` reached.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [4]
Traceback (most recent call last):
  File "/data/user/sofia/NN/GraphNet/examples/train_direction_reconstruction.py", line 249, in <module>
    main()
  File "/data/user/sofia/NN/GraphNet/examples/train_direction_reconstruction.py", line 245, in main
    train(config)
  File "/data/user/sofia/NN/GraphNet/examples/train_direction_reconstruction.py", line 210, in train
    results = get_predictions(
  File "/mnt/ceph1-npx/user/sofia/NN/GraphNet/src/graphnet/training/utils.py", line 184, in get_predictions
    assert len(prediction_columns) == predictions.shape[1]
AssertionError

ERROR conda.cli.main_run:execute(49): `conda run python /data/user/sofia/NN/GraphNet/examples/train_direction_reconstruction.py -i /data/ana/graphnet/tmp/dev_lvl5_NuE_NuMu_NuTau_Mirco/data/dev_lvl5_NuE_NuMu_NuTau_Mirco.db -o /data/user/sofia/NN/results -node_pooling dom_coarsening -batch_size 64 -epochs 5 -num_workers 30` failed. (See above for error)
```
The script runs on a conda env with `torch1.11, py3.10_cuda11.3_cudnn8.2.0_0`, failed when ran on NPX cluster.

**To Reproduce**
1. the executable: `/data/user/sofia/NN/jobs/job_dev_lvl5_NuE_NuMu_NuTau_Mirco.sh`
``` 
InFile=/data/ana/graphnet/tmp/dev_lvl5_NuE_NuMu_NuTau_Mirco/data/dev_lvl5_NuE_NuMu_NuTau_Mirco.db
OutFile=/data/user/sofia/NN/results
source /data/user/sofia/NN/miniconda3/etc/profile.d/conda.sh
conda run -p /data/user/sofia/NN/miniconda3/envs/graphnet_icetray python /data/user/sofia/NN/GraphNet/examples/train_direction_reconstruction.py -i $InFile -o $OutFile -node_pooling dom_coarsening -batch_size 64 -epochs 5 -num_workers 30
```
2. the submit file: `/data/user/sofia/NN/jobs/condor_dev_lvl5_NuE_NuMu_NuTau_Mirco.sub`
```
executable = /data/user/sofia/NN/jobs/job_dev_lvl5_NuE_NuMu_NuTau_Mirco.sh

initialdir     = /scratch/sofia/NNs/jobs
output         = $(initialdir)/output/test_batch64epochs5workers30.out
error          = $(initialdir)/error/test_batch64epochs5workers30.err
log            = $(initialdir)/logs/test_batch64epochs5workers30.log

#request_cpus = <num_cpus>
#request_memory = <mem_in_MB>
#request_disk = <disk_in_KB>
request_memory = 10000
request_gpus = 1

universe       = vanilla
notification   = never

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
queue 
```
3. submit on NPX: `ssh submit.icecube.wisc.edu; cd /scratch/sofia/NNs/jobs/ ; condor_submit condor_dev_lvl5_NuE_NuMu_NuTau_Mirco.sub` 

**Expected behavior**
Should train both zenith and azimuth without error.

**Comment by MortenHolmRep** [comment]
Sorry, I missed it on your first inquiry; Since you are using `AzimuthReconstructionWithKappa()` you also get a kappa prediction. This output needs to be reflected in line 213 `[config["target"] + "_pred"],`  ->  `[config["target"] + "_pred", config["target"] + "_kappa_pred"]`

I am closing the issue, if it does not resolve the issue please feel free to reopen the issue. I hope it works! :)
