### ISSUE TITLE
Cannot convert upgrade i3 files to sqlite anymore

### ISSUE THREAD

**Issue by RasmusOrsoe** [graphnet-team/graphnet#379]
**Describe the bug**
I used to be able to convert these files to sqlite. I then updated my main branch on my local fork. Now I can't convert the files. GraphNeT now incorrectly states that no gcd was given.

**To Reproduce**
1. Load cvmfs for upgrade
```
 eval `/cvmfs/icecube.opensciencegrid.org/py3-v4.1.1/setup.sh`
/cvmfs/icecube.opensciencegrid.org/users/upgrade-sim/software/icetray/branches/icecube_upgrade/build__py3-v4.1.1__osgvo-el7/env-shell.sh
```
3. install graphnet main
4. run script (adjust outdir)
5. see error

**Expected behavior**
should. work.

**Full traceback**
Please include the full error message to allow for debugging
```
Traceback (most recent call last):
  File "make_database.py", line 78, in <module>
FATAL (dataio): no frame to pop (I3File.cxx:142 in I3FramePtr dataio::I3File::pop_frame(I3Frame::Stream))
FATAL (dataio): no frame to pop (I3File.cxx:142 in I3FramePtr dataio::I3File::pop_frame(I3Frame::Stream))
graphnet: ERROR    2023-01-10 16:06:07 - I3TruthExtractor.error - No GCD file was provided and no G-frame was found. Exiting.
graphnet: ERROR    2023-01-10 16:06:07 - I3TruthExtractor.error - No GCD file was provided and no G-frame was found. Exiting.
    main_icecube_upgrade(backend)
  File "make_database.py", line 71, in main_icecube_upgrade
FATAL (dataio): no frame to pop (I3File.cxx:142 in I3FramePtr dataio::I3File::pop_frame(I3Frame::Stream))
graphnet: ERROR    2023-01-10 16:06:07 - I3TruthExtractor.error - No GCD file was provided and no G-frame was found. Exiting.
FATAL (dataio): no frame to pop (I3File.cxx:142 in I3FramePtr dataio::I3File::pop_frame(I3Frame::Stream))
    converter(inputs)
  File "/lustre/hpc/hep/pcs557/github/graphnet/src/graphnet/data/dataconverter.py", line 215, in __call__
graphnet: ERROR    2023-01-10 16:06:07 - I3TruthExtractor.error - No GCD file was provided and no G-frame was found. Exiting.
FATAL (dataio): no frame to pop (I3File.cxx:142 in I3FramePtr dataio::I3File::pop_frame(I3Frame::Stream))
    self.execute(filesets)
  File "/lustre/hpc/hep/pcs557/github/graphnet/src/graphnet/data/dataconverter.py", line 286, in execute
graphnet: ERROR    2023-01-10 16:06:07 - I3TruthExtractor.error - No GCD file was provided and no G-frame was found. Exiting.
FATAL (dataio): no frame to pop (I3File.cxx:142 in I3FramePtr dataio::I3File::pop_frame(I3Frame::Stream))
graphnet: ERROR    2023-01-10 16:06:07 - I3TruthExtractor.error - No GCD file was provided and no G-frame was found. Exiting.
    pool = self._iterate_over_individual_files(filesets)
  File "/lustre/hpc/hep/pcs557/github/graphnet/src/graphnet/data/dataconverter.py", line 331, in _iterate_over_individual_files
FATAL (dataio): no frame to pop (I3File.cxx:142 in I3FramePtr dataio::I3File::pop_frame(I3Frame::Stream))
graphnet: ERROR    2023-01-10 16:06:07 - I3TruthExtractor.error - No GCD file was provided and no G-frame was found. Exiting.
    self._process_file, tqdm(args, unit="file(s)", colour="green")
FATAL (dataio): no frame to pop (I3File.cxx:142 in I3FramePtr dataio::I3File::pop_frame(I3Frame::Stream))
  File "/cvmfs/icecube.opensciencegrid.org/py3-v4.1.1/RHEL_7_x86_64/lib/python3.7/multiprocessing/pool.py", line 748, in next
graphnet: ERROR    2023-01-10 16:06:07 - I3TruthExtractor.error - No GCD file was provided and no G-frame was found. Exiting.
FATAL (dataio): no frame to pop (I3File.cxx:142 in I3FramePtr dataio::I3File::pop_frame(I3Frame::Stream))
    raise value
graphnet: ERROR    2023-01-10 16:06:07 - I3TruthExtractor.error - No GCD file was provided and no G-frame was found. Exiting.
RuntimeError: no frame to pop (in I3FramePtr dataio::I3File::pop_frame(I3Frame::Stream))
FATAL (dataio): no frame to pop (I3File.cxx:142 in I3FramePtr dataio::I3File::pop_frame(I3Frame::Stream))
graphnet: ERROR    2023-01-10 16:06:07 - I3TruthExtractor.error - No GCD file was provided and no G-frame was found. Exiting.
FATAL (dataio): no frame to pop (I3File.cxx:142 in I3FramePtr dataio::I3File::pop_frame(I3Frame::Stream))
graphnet: ERROR    2023-01-10 16:06:07 - I3TruthExtractor.error - No GCD file was provided and no G-frame was found. Exiting.
```

**Additional context**

```
import logging
import os

import logging
import os

from graphnet.utilities.logging import get_logger

from graphnet.data.extractors import (
    I3FeatureExtractorIceCubeUpgrade,
    I3TruthExtractor,
    I3GenericExtractor,
    I3PISAExtractor,
    I3PulseNoiseTruthFlagIceCubeUpgrade,
)
from graphnet.data.parquet import ParquetDataConverter
from graphnet.data.sqlite import SQLiteDataConverter

logger = get_logger(level=logging.INFO)

CONVERTER_CLASS = {
    "sqlite": SQLiteDataConverter,
    "parquet": ParquetDataConverter,
}


def main_icecube_upgrade(backend: str):
    """Convert IceCube-Upgrade I3 files to intermediate `backend` format."""
    # Check(s)
    assert backend in CONVERTER_CLASS
    database_name = 'dev_step4_upgrade_028_21.11.2022_noise_test'
    #inputs = ["/data/sim/IceCubeUpgrade/noise/step4/880028"]
    inputs = ["/data/sim/IceCubeUpgrade/genie/step4/140028",
              "/data/sim/IceCubeUpgrade/genie/step4/141028",
              "/data/sim/IceCubeUpgrade/genie/step4/120028",
              "/data/sim/IceCubeUpgrade/genie/step4/160028",
              "/data/sim/IceCubeUpgrade/muongun/step4/130028",
              "/data/sim/IceCubeUpgrade/noise/step4/880028"]
              
    outdir = f"/data/user/rorsoe/databases/{database_name}"
    workers = 1
    converter = CONVERTER_CLASS[backend](
        [
            I3TruthExtractor(),
            I3PISAExtractor(),
          I3FeatureExtractorIceCubeUpgrade(
                "SplitInIcePulses"
            ),
          I3PulseNoiseTruthFlagIceCubeUpgrade(
                "SplitInIcePulses_TruthFlags"
            ),
            I3FeatureExtractorIceCubeUpgrade(
              "SplitIceCubePulsesTWSRT"
            ),
          I3PulseNoiseTruthFlagIceCubeUpgrade(
               "SplitIceCubePulsesTWSRT_TruthFlags"
           ),
          I3FeatureExtractorIceCubeUpgrade(
             "SplitInIcePulses_GraphSage_Pulses"
           ),
          I3PulseNoiseTruthFlagIceCubeUpgrade(
               "SplitInIcePulses_GraphSage_Predictions"
            ),
          I3PulseNoiseTruthFlagIceCubeUpgrade(
               "SplitInIcePulses_dynedge_Predictions"
            ),
          I3FeatureExtractorIceCubeUpgrade(
             "SplitInIcePulses_dynedge_Pulses"
           ),
        ],
        outdir + '/tmp',
        workers=workers,
        icetray_verbose=1,
        gcd_rescue = '/data/sim/IceCubeUpgrade/genie/step4/140028/GeoCalibDetectorStatus_ICUpgrade.v58.mixed.V0.i3.bz2'
    )
    os.makedirs(outdir + '/data/')
    converter(inputs)
    #if backend == "sqlite":
    #    converter.merge_files(outdir + '/data/' + database_name)


if __name__ == "__main__":
    backend = "sqlite"
    main_icecube_upgrade(backend)
```

**Comment by RasmusOrsoe** [comment]
I looked into this deeper and found this issue is not informative, as there are multiple underlying issues. I've created separate issues for each. See #381 #380 .
