### ISSUE TITLE
Problems Running the i3 convertor on Larger i3 files 

### ISSUE THREAD

**Issue by AishwaryaUMD** [graphnet-team/graphnet#388]
Description
The file "`convert_i3_files.py`" produces an error when calling on certain objects that are only in the P frames of the i3 files like "LineFit" but not all, like "SplitInIcePulsesTimeRange". 

To Reproduce
Run `convert_i3_files.py` on an i3 file from the following dataset https://iceprod2.icecube.wisc.edu/dataset/46df231ca54f11eaa7d6141877284d92 with the "LineFit" I3GenericExtractor key to see the following error message.  

Error Message 
Traceback (most recent call last):
  File "01_convert_i3_files.py", line 117, in <module>
    main_icecube86(args.backend)
  File "01_convert_i3_files.py", line 48, in main_icecube86
    converter(inputs)
  File "/data/condor_builds/users/avijai/IceCube/for_extraction/graphnet/src/graphnet/data/dataconverter.py", line 215, in __call__
    self.execute(filesets)
  File "/data/condor_builds/users/avijai/IceCube/for_extraction/graphnet/src/graphnet/data/dataconverter.py", line 286, in execute
    pool = self._iterate_over_individual_files(filesets)
  File "/data/condor_builds/users/avijai/IceCube/for_extraction/graphnet/src/graphnet/data/dataconverter.py", line 331, in _iterate_over_individual_files
    self._process_file, tqdm(args, unit="file(s)", colour="green")
  File "/data/condor_builds/users/avijai/IceCube/for_extraction/graphnet/src/graphnet/data/dataconverter.py", line 83, in wrapper
    output_file = process_method(self, *args)
  File "/data/condor_builds/users/avijai/IceCube/for_extraction/graphnet/src/graphnet/data/dataconverter.py", line 381, in _process_file
    self.save_data(data, output_file)
  File "/data/condor_builds/users/avijai/IceCube/for_extraction/graphnet/src/graphnet/data/parquet/parquet_dataconverter.py", line 32, in save_data
    awkward.to_parquet(awkward.from_iter(data), output_file)
  File "/data/condor_builds/users/avijai/IceCube/for_extraction/venv/lib/python3.7/site-packages/awkward/operations/convert.py", line 3072, in to_parquet
    writer.write_table(pyarrow.Table.from_batches([first]))
  File "/data/condor_builds/users/avijai/IceCube/for_extraction/venv/lib/python3.7/site-packages/pyarrow/parquet/core.py", line 1054, in write_table
    self.writer.write_table(table, row_group_size=row_group_size)
  File "pyarrow/_parquet.pyx", line 1772, in pyarrow._parquet.ParquetWriter.write_table
  File "pyarrow/error.pxi", line 121, in pyarrow.lib.check_status
pyarrow.lib.ArrowNotImplementedError: Lists with non-zero length null components are not supported

**Comment by MortenHolmRep** [comment]
Hey @AishwaryaUMD

A few replication questions:
- Are you running the most recent version of the code? 
- Have you made any modifications to [convert_i3_files.py](https://github.com/graphnet-team/graphnet/blob/main/examples/01_icetray/01_convert_i3_files.py)? i.e. changed what you extract, like removing `I3TruthExtractor()` or adding another one.

- As you are running on data with `Level 2 (pass2) IC86.2016 MuonGun` I assume you are using `main_icecube86` and not `main_icecube_upgrade`?

**Comment by AishwaryaUMD** [comment]
Hi @MortenHolmRep 

We are running a version of the code that's approximately a week old, (https://github.com/graphnet-team/graphnet/commit/332a86eded834bcab7b0f52e75d1c9c847e35262). We can pull the newest version and see if the same problem arises. We haven't made any modifications to the convertor itself and yes, we're using main_icecube86.

**Comment by AishwaryaUMD** [comment]
Using the newest version of the code, we're encountering the above error when running the convertor while calling on objects that fall in the I3RecoPulseSeriesMapMask type, apart from a couple special cases like SplitInIceDSTPulses and SplitInIcePulses.

**Comment by RasmusOrsoe** [comment]
@AishwaryaUMD I'm quite certain this error is produced because the `ParquetConverter` is finding empty lists (or similar) in one or more of the fields you have selected for extraction.

I would expect to see this bug if

- You are converting the files with a specified batch pattern that merges two or more files that don't all have the key(s) you're trying to extract.
- You are not using a batch pattern, but at least one of your i3 files don't have the key(s) you're trying to extract in all frames of the file.

To be sure, can you please confirm:

1. Have you specified a batch pattern?
2. Do you see the same issue if you run the code on just a single file?
3. Do you see the same issue if you switch the backend to sqlite instead of parquet? (graphnet has most functionality for sqlite - but don't let that keep you from parquet.)

Also, it would be very helpful for the eventual fix of this if you could do the following:

1. Share a minimal working example of your extraction script (that fails)
2. Provide a path on cobalt to some of the files that the code fails on


Rasmus

**Comment by AishwaryaUMD** [comment]
@RasmusOrsoe I haven't specified a batch pattern (not sure exactly what that is actually) and we have been trying to run it on a single i3 file only. Changing the backend to sqlite instead of parquet is working actually so thank you for the suggestion! 

The path on cobalt to some of the files that the code fails on is /data/sim/IceCube/2016/filtered/level2/MuonGun/21316. The extraction script used is the latest i3convertor under examples in the graphnet repository.
