### ISSUE TITLE
Example script `02_data/02_plot_feature_distributions.py` fails

### ISSUE THREAD

**Issue by JostMigenda** [graphnet-team/graphnet#393]
**Describe the bug**
As part of openjournals/joss-reviews#4971, I’ve started going through the example script. On my machine, running `02_data/02_plot_feature_distributions.py` fails; probably because `configs/datasets/test_data_sqlite.yml` points to an inaccessible file (`/groups/icecube/asogaard/…`).

**To Reproduce**
1. Start clean shell (on a machine that doesn’t have access to `/groups/icecube/asogaard/…`)
2. Activate environment with stand-alone install of GraphNeT. (I have not tested with an IceTray install yet.)
3. Run `python examples/02_data/02_plot_feature_distributions.py`

**Expected behavior**
Script runs successfully and produces output.

**Full traceback**
Please include the full error message to allow for debugging
```
graphnet: INFO     2023-01-26 17:12:10 - get_logger - Writing log to logs/graphnet_20230126-171210.log
graphnet: WARNING  2023-01-26 17:12:12 - warn_once - `icecube` not available. Some functionality may be missing.
Traceback (most recent call last):
  File "examples/02_data/02_plot_feature_distributions.py", line 94, in <module>
    main()
  File "examples/02_data/02_plot_feature_distributions.py", line 20, in main
    dataset = Dataset.from_config("configs/datasets/test_data_sqlite.yml")
  File "/…/graphnet/src/graphnet/data/dataset.py", line 60, in from_config
    return source._dataset_class(**source.dict())
  File "/…/graphnet/src/graphnet/utilities/config/dataset_config.py", line 164, in wrapper
    ret = init_fn(self, *args, **kwargs)
  File "/…/graphnet/src/graphnet/data/dataset.py", line 244, in __init__
    self._indices = self._get_all_indices()
  File "/…/graphnet/src/graphnet/data/sqlite/sqlite_dataset.py", line 83, in _get_all_indices
    self._establish_connection(0)
  File "/…/graphnet/src/graphnet/data/sqlite/sqlite_dataset.py", line 111, in _establish_connection
    self._conn = sqlite3.connect(self._path)
sqlite3.OperationalError: unable to open database file
```

**Additional context**
There are several other hardcoded paths to non-public files like that. I haven’t run into issues with the others yet; but perhaps this is a good opportunity to double-check if any of those should be fixed, too.

```
> igrep groups/icecube configs/datasets/*
configs/datasets/dev_lvl7_robustness_muon_neutrino_0000.yml:path: /groups/icecube/asogaard/data/example/dev_lvl7_robustness_muon_neutrino_0000.db
configs/datasets/PID_classification_last_one_lvl3MC.yml:path: /groups/icecube/petersen/GraphNetDatabaseRepository/Leon2022_DataAndMC_CSVandDB_StoppedMuons/last_one_lvl3MC.db
configs/datasets/test_data_sqlite.yml:path: /groups/icecube/asogaard/work/development/graphnet/data/tests/sqlite/oscNext_genie_level7_v02/oscNext_genie_level7_v02_first_5_frames.db
configs/datasets/training_example_data_parquet.yml:path: /groups/icecube/asogaard/work/development/graphnet/data/examples/parquet/prometheus/prometheus-events.parquet
configs/datasets/training_example_data_sqlite.yml:path: /groups/icecube/asogaard/work/development/graphnet/data/examples/sqlite/prometheus/prometheus-events.db
```

----

Additionally, when running `cd examples/` before step 3, there is a separate error message:
```
Traceback (most recent call last):
  File "02_data/02_plot_feature_distributions.py", line 94, in <module>
    main()
  File "02_data/02_plot_feature_distributions.py", line 20, in main
    dataset = Dataset.from_config("configs/datasets/test_data_sqlite.yml")
  File "/Users/jost/Documents/Academia/Papers/Reviews/JOSS GraphNeT/graphnet/src/graphnet/data/dataset.py", line 43, in from_config
    source = DatasetConfig.load(source)
  File "/Users/jost/Documents/Academia/Papers/Reviews/JOSS GraphNeT/graphnet/src/graphnet/utilities/config/base_config.py", line 25, in load
    with open(path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'configs/datasets/test_data_sqlite.yml'
```
Personally, I would find it nice to be able to run all example scripts from within the `examples/` directory (or even one of the numbered subdirectories) so the `logs/` and `outputs/` directories don’t pollute the root directory of the repo; but if they need to be run from a specific directory, that should be mentioned explicitly in the README or that script’s `--help` text.

**Comment by JostMigenda** [comment]
Just noticed that the same issue occurs in `examples/04_training/01_train_model.py` when running it with the default dataset config (`--dataset-config configs/datasets/training_example_data_sqlite.yml`):
```
Traceback (most recent call last):
  File "examples/04_training/01_train_model.py", line 159, in <module>
    main(
  File "examples/04_training/01_train_model.py", line 70, in main
    dataloaders = DataLoader.from_dataset_config(
  File "/Users/jost/Documents/Academia/Papers/Reviews/JOSS GraphNeT/graphnet/src/graphnet/data/dataloader.py", line 66, in from_dataset_config
    datasets = Dataset.from_config(config)
  File "/Users/jost/Documents/Academia/Papers/Reviews/JOSS GraphNeT/graphnet/src/graphnet/data/dataset.py", line 52, in from_config
    return cls._construct_datasets_from_dict(source)
  File "/Users/jost/Documents/Academia/Papers/Reviews/JOSS GraphNeT/graphnet/src/graphnet/data/dataset.py", line 80, in _construct_datasets_from_dict
    dataset = Dataset.from_config(config)
  File "/Users/jost/Documents/Academia/Papers/Reviews/JOSS GraphNeT/graphnet/src/graphnet/data/dataset.py", line 60, in from_config
    return source._dataset_class(**source.dict())
  File "/Users/jost/Documents/Academia/Papers/Reviews/JOSS GraphNeT/graphnet/src/graphnet/utilities/config/dataset_config.py", line 164, in wrapper
    ret = init_fn(self, *args, **kwargs)
  File "/Users/jost/Documents/Academia/Papers/Reviews/JOSS GraphNeT/graphnet/src/graphnet/data/dataset.py", line 246, in __init__
    self._indices = self._resolve_string_selection_to_indices(
  File "/Users/jost/Documents/Academia/Papers/Reviews/JOSS GraphNeT/graphnet/src/graphnet/data/dataset.py", line 356, in _resolve_string_selection_to_indices
    return self._string_selection_resolver.resolve(selection)
  File "/Users/jost/Documents/Academia/Papers/Reviews/JOSS GraphNeT/graphnet/src/graphnet/data/utilities/string_selection_resolver.py", line 95, in resolve
    df_selection = self._query_selection_from_dataset(selection)
  File "/Users/jost/Documents/Academia/Papers/Reviews/JOSS GraphNeT/graphnet/src/graphnet/data/utilities/string_selection_resolver.py", line 215, in _query_selection_from_dataset
    data=self._dataset.query_table(
  File "/Users/jost/Documents/Academia/Papers/Reviews/JOSS GraphNeT/graphnet/src/graphnet/data/sqlite/sqlite_dataset.py", line 61, in query_table
    self._establish_connection(index)
  File "/Users/jost/Documents/Academia/Papers/Reviews/JOSS GraphNeT/graphnet/src/graphnet/data/sqlite/sqlite_dataset.py", line 111, in _establish_connection
    self._conn = sqlite3.connect(self._path)
sqlite3.OperationalError: unable to open database file
```

I also noticed that that script runs from any folder by using [`graphnet.constants.CONFIG_DIR`](https://github.com/graphnet-team/graphnet/blob/dbaa88506b2d61f91ff3040792bf89f8b8c69ee3/src/graphnet/constants.py#L33) instead of hard-coding the relative path to the config file.
