### ISSUE TITLE
empty batch due to collate_fn()

### ISSUE THREAD

**Issue by Aske-Rosted** [graphnet-team/graphnet#424]
The bug happens when your batch happens to be _completely_ filled with evens with n_pulses < 1

**To Reproduce**
Hard to reproduce due to random behavior of batching and not using shared data. 

**Expected behavior**
I would expect for some kind of handling of situation where all events in batch are "empty" eg. skipping prediction on batch. 

**Full traceback**
Predicting DataLoader 0:  18%|████████████████████▋                                                                                            | 754/4117 [01:26<06:26,  8.71 batch(es)/s]Traceback (most recent call last):
  File "/cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/RHEL_7_x86_64/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/RHEL_7_x86_64/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/misc/home/aske/.vscode-server/extensions/ms-python.python-2022.20.2/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/misc/home/aske/.vscode-server/extensions/ms-python.python-2022.20.2/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/misc/home/aske/.vscode-server/extensions/ms-python.python-2022.20.2/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/misc/home/aske/.vscode-server/extensions/ms-python.python-2022.20.2/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 322, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/misc/home/aske/.vscode-server/extensions/ms-python.python-2022.20.2/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 136, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/misc/home/aske/.vscode-server/extensions/ms-python.python-2022.20.2/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/disk20/users/aske/personal_scripts/predict_with_pretrained.py", line 208, in <module>
    args.additional_attributes,
  File "/disk20/users/aske/personal_scripts/predict_with_pretrained.py", line 143, in main
    distribution_strategy="ddp_find_unused_parameters_false"
  File "/misc/disk20/users/aske/graphnet/src/graphnet/models/model.py", line 185, in predict_as_dataframe
    distribution_strategy=distribution_strategy,
  File "/misc/disk20/users/aske/graphnet/src/graphnet/models/standard_model.py", line 176, in predict
    distribution_strategy=distribution_strategy,
  File "/misc/disk20/users/aske/graphnet/src/graphnet/models/model.py", line 136, in predict
    predictions_list = self._inference_trainer.predict(self, dataloader)
  File "/home/aske/IG/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 950, in predict
    self._predict_impl, model, dataloaders, datamodule, return_predictions, ckpt_path
  File "/home/aske/IG/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/aske/IG/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 996, in _predict_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/aske/IG/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1166, in _run
    results = self._run_stage()
  File "/home/aske/IG/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1251, in _run_stage
    return self._run_predict()
  File "/home/aske/IG/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1311, in _run_predict
    return self.predict_loop.run()
  File "/home/aske/IG/lib/python3.7/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/home/aske/IG/lib/python3.7/site-packages/pytorch_lightning/loops/dataloader/prediction_loop.py", line 103, in advance
    dataloader_iter, self.current_dataloader_idx, dl_max_batches, self.num_dataloaders
  File "/home/aske/IG/lib/python3.7/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/home/aske/IG/lib/python3.7/site-packages/pytorch_lightning/loops/epoch/prediction_epoch_loop.py", line 89, in advance
    batch_idx, batch = next(dataloader_iter)
  File "/home/aske/IG/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/home/aske/IG/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "/home/aske/IG/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/home/aske/IG/lib/python3.7/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/home/aske/IG/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/aske/IG/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/misc/disk20/users/aske/graphnet/src/graphnet/data/dataloader.py", line 18, in collate_fn
    return Batch.from_data_list(graphs)
  File "/home/aske/IG/lib/python3.7/site-packages/torch_geometric/data/batch.py", line 72, in from_data_list
    add_batch=not isinstance(data_list[0], Batch),
IndexError: list index out of range

**Additional context**
collate_fn() call happens in pytorch domain and therefore I am unable to figure out where to implement a fix.

This might not be exclusive to just the prediction step however that is the only place where I have encountered it.

**Comment by Aske-Rosted** [comment]
Have looked more into this and it looks like an issue earlier in the data production on my end.
