### ISSUE TITLE
Training with GPU

### ISSUE THREAD

**Issue by AishwaryaUMD** [graphnet-team/graphnet#445]
Description
The file 02_train_model_without_configs.py produces an error when run with GPU. 

To Reproduce 
Run the file 02_train_model_without_configs.py with GPU (I used the following command python3 02_train_model_without_configs.py --gpus 0). 

Error Message 
Sanity Checking: 0it [00:00, ?it/s]Traceback (most recent call last):
  File "02_train_model_without_configs.py", line 212, in <module>
    main(
  File "02_train_model_without_configs.py", line 135, in main
    model.fit(
  File "/home/avijai/for_nn/graphnet/src/graphnet/models/model.py", line 106, in fit
    self._trainer.fit(
  File "/home/avijai/for_nn/miniconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/home/avijai/for_nn/miniconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 36, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/home/avijai/for_nn/miniconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 88, in launch
    return function(*args, **kwargs)
  File "/home/avijai/for_nn/miniconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/home/avijai/for_nn/miniconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1112, in _run
    results = self._run_stage()
  File "/home/avijai/for_nn/miniconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1191, in _run_stage
    self._run_train()
  File "/home/avijai/for_nn/miniconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1204, in _run_train
    self._run_sanity_check()
  File "/home/avijai/for_nn/miniconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1276, in _run_sanity_check
    val_loop.run()
  File "/home/avijai/for_nn/miniconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/avijai/for_nn/miniconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 152, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/home/avijai/for_nn/miniconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/avijai/for_nn/miniconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 121, in advance
    batch = next(data_fetcher)
  File "/home/avijai/for_nn/miniconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/utilities/fetching.py", line 184, in __next__
    return self.fetching_function()
  File "/home/avijai/for_nn/miniconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/utilities/fetching.py", line 265, in fetching_function
    self._fetch_next_batch(self.dataloader_iter)
  File "/home/avijai/for_nn/miniconda3/envs/graphnet/lib/python3.8/site-packages/pytorch_lightning/utilities/fetching.py", line 280, in _fetch_next_batch
    batch = next(iterator)
  File "/home/avijai/for_nn/miniconda3/envs/graphnet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/home/avijai/for_nn/miniconda3/envs/graphnet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "/home/avijai/for_nn/miniconda3/envs/graphnet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/home/avijai/for_nn/miniconda3/envs/graphnet/lib/python3.8/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/avijai/for_nn/miniconda3/envs/graphnet/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/avijai/for_nn/miniconda3/envs/graphnet/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/home/avijai/for_nn/graphnet/src/graphnet/training/utils.py", line 29, in collate_fn
    return Batch.from_data_list(graphs)
  File "/home/avijai/for_nn/miniconda3/envs/graphnet/lib/python3.8/site-packages/torch_geometric/data/batch.py", line 68, in from_data_list
    batch, slice_dict, inc_dict = collate(
  File "/home/avijai/for_nn/miniconda3/envs/graphnet/lib/python3.8/site-packages/torch_geometric/data/collate.py", line 84, in collate
    value, slices, incs = _collate(attr, values, data_list, stores,
  File "/home/avijai/for_nn/miniconda3/envs/graphnet/lib/python3.8/site-packages/torch_geometric/data/collate.py", line 145, in _collate
    storage = elem.storage()._new_shared(numel)
  File "/home/avijai/for_nn/miniconda3/envs/graphnet/lib/python3.8/site-packages/torch/storage.py", line 487, in _new_shared
    untyped_storage = module._UntypedStorage._new_shared(size * cls().element_size())
  File "/home/avijai/for_nn/miniconda3/envs/graphnet/lib/python3.8/site-packages/torch/storage.py", line 172, in _new_shared
    return cls._new_using_filename(size)
RuntimeError: torch_shm_manager at "/home/avijai/for_nn/miniconda3/envs/graphnet/lib/python3.8/site-packages/torch/bin/torch_shm_manager": could not generate a random directory for manager socket

**Comment by RasmusOrsoe** [comment]
@AishwaryaUMD did you change the data in the example to something else, or do any other kind of modifications?

**Comment by AishwaryaUMD** [comment]
@RasmusOrsoe No, I just used the prometheus dataset

**Comment by RasmusOrsoe** [comment]
@AishwaryaUMD I'm not able to reproduce this error. 

When I look up this error it seems to appear as a software issue for pytorch usually on OSX.

Could you please list here your system information along with pytorch version?

**Comment by AishwaryaUMD** [comment]
@RasmusOrsoe Sorry for the delayed response. So I'm jupyter ml (cluster) to run this, and the torch version is Version: 1.11.0+cu115.

**Comment by RasmusOrsoe** [comment]
@AishwaryaUMD I will need more details if I am to have any hope in helping with this. 

- How exactly are you running this example on a cluster using jupyter?
- - Are you able to run this example outside jupyter?

**Comment by asogaard** [comment]
Hi @AishwaryaUMD,

Let checking in to see whether this issue is still active: Did you manage to resolve your problem? If not, could you please follow @RasmusOrsoe's suggestion above and provide a few more details on the setup your using to run the script in question, such that we can better help debugging? 😊

**Comment by RasmusOrsoe** [comment]
@AishwaryaUMD ping

**Comment by AishwaryaUMD** [comment]
@RasmusOrsoe @asogaard  so sorry for the late response, I managed to solve the issue, it was just a problem with the way I was running it on jupyter-ml. Thank you for your quick responses!
