### ISSUE TITLE
ImportError: cannot import name 'lightning_environment' from 'pytorch_lightning.plugins.environments

### ISSUE THREAD

**Issue by RasmusOrsoe** [graphnet-team/graphnet#453]
**Describe the bug**

In pytorch lightning version 1.9.2, the import 

`from pytorch_lightning.plugins.environments import lightning_environment`

fails with 
```

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'lightning_environment' from 'pytorch_lightning.plugins.environments' (/home/kleonard/.local/lib/python3.7/site-packages/pytorch_lightning/plugins/environments/__init__.py)

```

We have no upper limit on pytorch_lightning version currently - however, as the code stands, it seems it's not compatible with >`1.7.3`

If you downgrade to 1.7.3. it seems like you also need to downgrade `markupsafe==2.0.1`

**To Reproduce**
1. install graphnet on a new enviroment with no prior installation of pytorch lightning or torch
2. Run this
```
 import pytorch_lightning

 pytorch_lightning.__version__

 from pytorch_lightning.plugins.environments import lightning_environment
```

**Expected behavior**
Should run without issues.

**Full traceback**
Please include the full error message to allow for debugging
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'lightning_environment' from 'pytorch_lightning.plugins.environments' (/home/kleonard/.local/lib/python3.7/site-packages/pytorch_lightning/plugins/environments/__init__.py)
```

**Additional context**
We either need to update graphnet to be compatible with latest versions of pytorch lightning, or change the dependencies to reflect which versions we are compatible with. I'm personally in favor of updating graphnet.

**Comment by RasmusOrsoe** [comment]
Related: https://www.kaggle.com/code/rasmusrse/graphnet-example/comments#2186145
