### ISSUE TITLE
self.warnonce() in "src/graphnet/models/graphs/graph_definition.py" is not a class method

### ISSUE THREAD

**Issue by ArturoLlorente** [graphnet-team/graphnet#600]
**Describe the bug**
In "src/graphnet/models/graphs/graph_definition.py", Lines 119 and 255 there is a warning `self.warnonce()`. It seems to be a method inherited from the class `Logger()` in "src/graphnet/utilities/logging.py", which has no such method. Although there is  method called `warning_once()`, which might be the correct one.

**To Reproduce**
1. Train a model with the features from KAGGLE: `["x", "y", "z", "time", "charge", "auxiliary"]`

**Expected behavior**
The warning is shown as:
 - Cannot assign graph['x']. This field is reserved for node features. Please rename your input feature.

**Full traceback**
```
Original Traceback (most recent call last):
  File "/home/iwsatlas1/llorente/.conda/envs/graphnet/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/iwsatlas1/llorente/.conda/envs/graphnet/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/iwsatlas1/llorente/.conda/envs/graphnet/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/remote/ceph/user/l/llorente/graphnet/src/graphnet/data/dataset/dataset.py", line 438, in __getitem__
    graph = self._create_graph(features, truth, node_truth, loss_weight)
  File "/remote/ceph/user/l/llorente/graphnet/src/graphnet/data/dataset/dataset.py", line 626, in _create_graph
    graph = self._graph_definition(
  File "/home/iwsatlas1/llorente/.conda/envs/graphnet/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/remote/ceph/user/l/llorente/graphnet/src/graphnet/models/graphs/graph_definition.py", line 146, in forward
    graph = self._add_features_individually(
  File "/remote/ceph/user/l/llorente/graphnet/src/graphnet/models/graphs/graph_definition.py", line 255, in _add_features_individually
    self.warnonce(
  File "/home/iwsatlas1/llorente/.conda/envs/graphnet/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'KNNGraph' object has no attribute 'warnonce'

```

**Additional context**
When replacing with `self.warning_once()`, proper behaviour is reached

**Comment by AMHermansen** [comment]
Good catch, thank you!
